### ISSUE TITLE
Old SnapKit Dependency

### ISSUE THREAD

**Issue by Swisyn** [springwong/SnapKitten#3]
Hello, i saw your medium blog post and wanted to try this lib but seems like it's snapkit version is too old.

[!] CocoaPods could not find compatible versions for pod "SnapKit":
  In snapshot (Podfile.lock):
    SnapKit (= 4.0.0, ~> 4.0)

  In Podfile:
    SnapKit (~> 4.0)

    SnapKitten was resolved to 1.2.0, which depends on
      SnapKit (~> 3.2.0)

**Comment by springwong** [comment]
Hello, updated to version 1.2.6 which support SnapKit 4.0.
feel free to ask any other question =]

Spring

2018-04-28 17:59 GMT+08:00 Cüneyt AYYILDIZ <notifications@github.com>:
